joint_motor_pos_mapping:
  shoulder_pan:
    motor_pos: 2047
    joint_pos: 0
  shoulder_lift:
    motor_pos: 2047
    joint_pos: 0
  elbow_flex:
    motor_pos: 2047
    joint_pos: 0
  wrist_flex:
    motor_pos: 2047
    joint_pos: 0
  wrist_roll:
    motor_pos: 2047
    joint_pos: 0
  gripper:
    motor_pos: 2047
    joint_pos: 0

#1 radian = 651.89 motor position increment
joint_to_motor_scale:
  shoulder_pan: 651.89
  shoulder_lift: 651.89
  elbow_flex: 651.89
  wrist_flex: 651.89
  wrist_roll: 651.89
  gripper: 651.89
