topic:
  /vr_controller/joint_cmd: /right/vr_controller/joint_cmd
  # /joint_states: /right/joint_states
  /robot_control/motor_cmd: /right/robot_control/motor_cmd
  /robot_control/motor_state: /right/robot_control/motor_state
  # /tf: /right/tf

node: right_lerobot_vr_controller
