vr_to_arm_tf:
  #tf link mapping
  gripper_frame_link: wrist_right
gripper_world_frame: base_link
vr_world_frame: world_vr

# IK solver tolerances configuration
ik_tolerances:
  position_tolerance: 0.01    # Position tolerance in meters
  orientation_tolerance: 0.5  # Orientation tolerance in radians
