vr_to_arm_tf:
  #tf link mapping
  gripper_frame_link: wrist_right
gripper_world_frame: base_link
vr_world_frame: world_vr

# IK solver tolerances configuration
ik_tolerances:
  position_tolerance: 0.03    # Position tolerance in meters
  orientation_tolerance: 0.02  # Orientation tolerance in radians
  xy_max_reach: 0.6           # Maximum xy plane reach limit in meters

joy_config:
  trigger_config:
    trigger_to_gripper_scale: 0.0068  # Scale factor for trigger input to gripper position
    joint_mappings:
      # {joint name: vr topic}
      gripper: /vr/controller_right/joy
  axes_config:
    # meter unit input from axes
    z_advance_scale: -0.003
    # radian unit input from axes
    z_clockwise_rotate_scale: -0.03

joint_pose:
  home_pose:
    joint_name: 
      - shoulder_pan
      - shoulder_lift
      - elbow_flex
      - wrist_flex
      - wrist_roll
      - gripper
    position:
      - 0.0
      - -1.5370691374311618
      - 1.522
      - 0.0
      - 0.0
      - 0.0

joint_filter:
  alpha: 0.5
